name: Build and publish

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  PELICANOPTS: "--verbose"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check out pelican-plugins
      uses: actions/checkout@v3
      with:
        repository: getpelican/pelican-plugins
        path: pelican-plugins

    - name: Check out pelican-themes
      uses: actions/checkout@v3
      with:
        repository: getpelican/pelican-themes
        path: pelican-themes

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        cache: pip
        cache-dependency-path: "**/requirements.txt"

    - name: Install Pelican, plugins, and themes
      run: |
        python -m pip install --upgrade -r requirements.txt

        pelican-themes --symlink $(realpath pelican-themes/pelican-bootstrap3)
        pelican-themes --list --verbose

    - name: Build
      run: make publish

    - name: Publish to GitHub pages
      if: success() && github.event_name == 'push'
      run: make github
